mingw: Fix builds on f33 mingw
Fedora 33's mingw moans about:

In file included from ../tests/test-bitmap.c:12:
/home/dgilbert/git/migpull/include/qemu/osdep.h:76: error: "__USE_MINGW_ANSI_STDIO" redefined [-Werror]
   76 | #define __USE_MINGW_ANSI_STDIO 1
      |

the fix is to make sure osdep.h is the first include - which is our
rule anyway; but one we broke in a couple of places.

Signed-off-by: Dr. David Alan Gilbert <dgilbert@redhat.com>
Message-Id: <20201008174359.157627-1-dgilbert@redhat.com>
Reviewed-by: Thomas Huth <thuth@redhat.com>